export interface PeptideTemplate {
  id: string;
  name: string;
  category: string;
  defaultVialSize: number;
  vialUnit: 'mg' | 'mcg' | 'mL';
  defaultBacWater: number;
  targetDose: number;
  doseUnit: 'mg' | 'mcg' | 'mL';
  defaultStock: number;
  frequency: 'daily' | 'weekly' | '2x_week' | '3x_week';
  frequencyLabel: string;
  halfLifeDays: number;
  maxFridgeDays: number;
  description: string;
  presetLow: number;
  presetStandard: number;
  presetHigh: number;
  activeDays: string[];
  injectionTime: string;
}

export const DEFAULT_PEPTIDES: PeptideTemplate[] = [
  {
    id: 'retatrutide',
    name: 'Retatrutide',
    category: 'GLP-1 / GIP / GCG Tri-Agonist',
    defaultVialSize: 10,
    vialUnit: 'mg',
    defaultBacWater: 1.0,
    targetDose: 2.0,
    doseUnit: 'mg',
    defaultStock: 10,
    frequency: 'weekly',
    frequencyLabel: 'Mingguan (Weekly)',
    halfLifeDays: 6.0,
    maxFridgeDays: 56,
    description: 'Triple agonist reseptor metabolik untuk optimalisasi energi dan pengelolaan glukosa.',
    presetLow: 1.0,
    presetStandard: 2.0,
    presetHigh: 4.0,
    activeDays: ['Sen'],
    injectionTime: '08:00',
  },
  {
    id: 'bpc-157',
    name: 'BPC 157',
    category: 'Healing & Gut Support',
    defaultVialSize: 10,
    vialUnit: 'mg',
    defaultBacWater: 2.0,
    targetDose: 0.5,
    doseUnit: 'mg',
    defaultStock: 10,
    frequency: 'daily',
    frequencyLabel: 'Harian (Daily)',
    halfLifeDays: 0.5,
    maxFridgeDays: 28,
    description: 'Peptida regeneratif sintetis untuk percepatan perbaikan mukosa usus, tendon, dan ligamen.',
    presetLow: 0.25,
    presetStandard: 0.5,
    presetHigh: 1.0,
    activeDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    injectionTime: '08:00',
  },
  {
    id: 'cjc-ipa',
    name: 'CJC + IPA',
    category: 'GH Secretagogue & Recovery (GHRH+GHRP)',
    defaultVialSize: 10,
    vialUnit: 'mg',
    defaultBacWater: 2.0,
    targetDose: 0.3,
    doseUnit: 'mg',
    defaultStock: 10,
    frequency: 'daily',
    frequencyLabel: 'Harian (Daily)',
    halfLifeDays: 0.2,
    maxFridgeDays: 28,
    description: 'Kombinasi sinergis CJC-1295 No DAC dan Ipamorelin untuk memicu pelepasan Growth Hormone alami.',
    presetLow: 0.15,
    presetStandard: 0.3,
    presetHigh: 0.5,
    activeDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    injectionTime: '21:00',
  },
  {
    id: 'ghk-cu',
    name: 'GHK-Cu',
    category: 'Tissue Repair / Anti-Aging',
    defaultVialSize: 50,
    vialUnit: 'mg',
    defaultBacWater: 3.0,
    targetDose: 2.0,
    doseUnit: 'mg',
    defaultStock: 8,
    frequency: 'daily',
    frequencyLabel: 'Harian (Daily)',
    halfLifeDays: 0.5,
    maxFridgeDays: 28,
    description: 'Kompleks peptida tembaga untuk sintesis kolagen, elastisitas kulit, dan remodeling jaringan.',
    presetLow: 1.0,
    presetStandard: 2.0,
    presetHigh: 3.0,
    activeDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    injectionTime: '08:00',
  },
  {
    id: 'kisspeptin',
    name: 'Kisspeptin',
    category: 'Hormonal Axis Support',
    defaultVialSize: 10,
    vialUnit: 'mg',
    defaultBacWater: 2.0,
    targetDose: 0.2,
    doseUnit: 'mg',
    defaultStock: 10,
    frequency: '3x_week',
    frequencyLabel: '3x Seminggu',
    halfLifeDays: 0.3,
    maxFridgeDays: 28,
    description: 'Neuropeptida regulator poros GnRH-LH-FSH untuk mendukung modulasi hormonal endogen.',
    presetLow: 0.1,
    presetStandard: 0.2,
    presetHigh: 0.4,
    activeDays: ['Sen', 'Rab', 'Jum'],
    injectionTime: '08:00',
  },
  {
    id: 'mots-c',
    name: 'MOTS-c',
    category: 'Mitochondrial Energy',
    defaultVialSize: 20,
    vialUnit: 'mg',
    defaultBacWater: 2.0,
    targetDose: 5.0,
    doseUnit: 'mg',
    defaultStock: 10,
    frequency: '3x_week',
    frequencyLabel: '3x Seminggu',
    halfLifeDays: 0.8,
    maxFridgeDays: 28,
    description: 'Peptida turunan mitokondria untuk metabolisme energi seluler dan sensitivitas insulin.',
    presetLow: 2.5,
    presetStandard: 5.0,
    presetHigh: 10.0,
    activeDays: ['Sen', 'Rab', 'Jum'],
    injectionTime: '08:00',
  },
  {
    id: 'lc526',
    name: 'LC526',
    category: 'Fat Metabolism & Liver',
    defaultVialSize: 10,
    vialUnit: 'mL',
    defaultBacWater: 0.0,
    targetDose: 1.0,
    doseUnit: 'mL',
    defaultStock: 10,
    frequency: 'daily',
    frequencyLabel: 'Harian (Daily)',
    halfLifeDays: 1.0,
    maxFridgeDays: 60,
    description: 'Formulasi asam amino lipotropik untuk mendukung pemecahan lemak dan fungsi hati.',
    presetLow: 0.5,
    presetStandard: 1.0,
    presetHigh: 2.0,
    activeDays: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'],
    injectionTime: '08:00',
  },
  {
    id: 'tirzepatide',
    name: 'Tirzepatide',
    category: 'GLP-1 / GIP Dual Agonist',
    defaultVialSize: 10,
    vialUnit: 'mg',
    defaultBacWater: 1.0,
    targetDose: 2.5,
    doseUnit: 'mg',
    defaultStock: 10,
    frequency: 'weekly',
    frequencyLabel: 'Mingguan (Weekly)',
    halfLifeDays: 5.0,
    maxFridgeDays: 56,
    description: 'GIP dan GLP-1 receptor dual agonist untuk kontrol nafsu makan dan regulasi glikemik.',
    presetLow: 2.5,
    presetStandard: 5.0,
    presetHigh: 7.5,
    activeDays: ['Sen'],
    injectionTime: '08:00',
  },
  {
    id: 'semaglutide',
    name: 'Semaglutide',
    category: 'GLP-1 Receptor Agonist',
    defaultVialSize: 5,
    vialUnit: 'mg',
    defaultBacWater: 1.0,
    targetDose: 0.5,
    doseUnit: 'mg',
    defaultStock: 10,
    frequency: 'weekly',
    frequencyLabel: 'Mingguan (Weekly)',
    halfLifeDays: 7.0,
    maxFridgeDays: 56,
    description: 'GLP-1 long-acting analog untuk regulasi nafsu makan dan metabolisme glukosa.',
    presetLow: 0.25,
    presetStandard: 0.5,
    presetHigh: 1.0,
    activeDays: ['Sen'],
    injectionTime: '08:00',
  },
];


// Shared body-map data used by the rotation component. Keeping this here avoids
// duplicate site definitions and gives the SVG map a single source of truth.
export const INJECTION_SITES = [
  { id: 'KA', code: 'KA', name: 'Kanan Atas', desc: 'Perut kanan atas', side: 'right', cx: 124, cy: 92 },
  { id: 'KiA', code: 'KiA', name: 'Kiri Atas', desc: 'Perut kiri atas', side: 'left', cx: 196, cy: 92 },
  { id: 'KB', code: 'KB', name: 'Kanan Bawah', desc: 'Perut kanan bawah', side: 'right', cx: 124, cy: 188 },
  { id: 'KiB', code: 'KiB', name: 'Kiri Bawah', desc: 'Perut kiri bawah', side: 'left', cx: 196, cy: 188 },
];

// Backward-compatible export for older components. New code should prefer
// DEFAULT_PEPTIDES and map the fields it needs explicitly.
export const MASTER_PEPTIDE_DATABASE = DEFAULT_PEPTIDES;
